export const COURSES = [
  {
    id: 1,
    title: 'Full-Stack Web Development with MERN',
    instructor: 'Dr. Sarah Mitchell',
    category: 'Web Development',
    level: 'Intermediate',
    price: 4999,
    originalPrice: 8999,
    rating: 4.8,
    reviews: 2340,
    students: 12450,
    duration: '48 hours',
    lessons: 124,
    image: null,
    color: '#00d4ff',
    description: 'Master MongoDB, Express, React, and Node.js to build modern full-stack web applications from scratch.',
    tags: ['React', 'Node.js', 'MongoDB', 'Express'],
    featured: true,
    bestseller: true,
    curriculum: [
      { section: 'Getting Started', lessons: ['Course Introduction', 'Environment Setup', 'JavaScript Refresher'] },
      { section: 'React Fundamentals', lessons: ['JSX & Components', 'Props & State', 'Hooks Deep Dive', 'React Router'] },
      { section: 'Node.js & Express', lessons: ['REST APIs', 'Middleware', 'Authentication', 'File Uploads'] },
      { section: 'MongoDB', lessons: ['Schema Design', 'CRUD Operations', 'Aggregation', 'Indexing'] },
    ]
  },
  {
    id: 2,
    title: 'Advanced Python for Data Science',
    instructor: 'Prof. James Chen',
    category: 'Data Science',
    level: 'Advanced',
    price: 5999,
    originalPrice: 10999,
    rating: 4.9,
    reviews: 3120,
    students: 18900,
    duration: '60 hours',
    lessons: 156,
    image: null,
    color: '#7c3aed',
    description: 'Deep dive into Python for machine learning, data analysis, and visualization with real-world projects.',
    tags: ['Python', 'Pandas', 'TensorFlow', 'Jupyter'],
    featured: true,
    bestseller: false,
    curriculum: [
      { section: 'Python Advanced', lessons: ['Decorators', 'Generators', 'Context Managers'] },
      { section: 'Data Analysis', lessons: ['NumPy', 'Pandas', 'Matplotlib', 'Seaborn'] },
      { section: 'Machine Learning', lessons: ['Scikit-learn', 'Model Evaluation', 'Feature Engineering'] },
    ]
  },
  {
    id: 3,
    title: 'UI/UX Design Masterclass',
    instructor: 'Emma Rodriguez',
    category: 'Design',
    level: 'Beginner',
    price: 3499,
    originalPrice: 6999,
    rating: 4.7,
    reviews: 1890,
    students: 9200,
    duration: '36 hours',
    lessons: 92,
    image: null,
    color: '#ff3d9a',
    description: 'Learn Figma, design systems, and user research to create stunning, user-centered digital products.',
    tags: ['Figma', 'Prototyping', 'UX Research', 'Design Systems'],
    featured: false,
    bestseller: true,
    curriculum: [
      { section: 'Design Foundations', lessons: ['Color Theory', 'Typography', 'Layout Principles'] },
      { section: 'Figma Mastery', lessons: ['Components', 'Auto Layout', 'Prototyping', 'Handoff'] },
    ]
  },
  {
    id: 4,
    title: 'Cloud Architecture with AWS',
    instructor: 'Michael Torres',
    category: 'Cloud Computing',
    level: 'Advanced',
    price: 6999,
    originalPrice: 12999,
    rating: 4.8,
    reviews: 1560,
    students: 7800,
    duration: '52 hours',
    lessons: 138,
    image: null,
    color: '#ff6b35',
    description: 'Design, deploy and manage scalable cloud solutions using Amazon Web Services core services.',
    tags: ['AWS', 'EC2', 'S3', 'Lambda', 'Docker'],
    featured: true,
    bestseller: false,
    curriculum: [
      { section: 'AWS Fundamentals', lessons: ['IAM', 'EC2', 'VPC', 'S3'] },
      { section: 'Serverless', lessons: ['Lambda', 'API Gateway', 'DynamoDB'] },
    ]
  },
  {
    id: 5,
    title: 'Cybersecurity & Ethical Hacking',
    instructor: 'Dr. Raj Patel',
    category: 'Security',
    level: 'Intermediate',
    price: 5499,
    originalPrice: 9999,
    rating: 4.6,
    reviews: 2100,
    students: 10300,
    duration: '44 hours',
    lessons: 112,
    image: null,
    color: '#00e5a0',
    description: 'Learn penetration testing, vulnerability assessment, and how to secure modern applications.',
    tags: ['Kali Linux', 'Penetration Testing', 'Network Security'],
    featured: false,
    bestseller: false,
    curriculum: [
      { section: 'Security Fundamentals', lessons: ['CIA Triad', 'Threat Modeling', 'Cryptography'] },
      { section: 'Ethical Hacking', lessons: ['Reconnaissance', 'Exploitation', 'Post-Exploitation'] },
    ]
  },
  {
    id: 6,
    title: 'Mobile App Development with React Native',
    instructor: 'Lisa Wang',
    category: 'Mobile Development',
    level: 'Intermediate',
    price: 4499,
    originalPrice: 7999,
    rating: 4.7,
    reviews: 1780,
    students: 8600,
    duration: '40 hours',
    lessons: 104,
    image: null,
    color: '#00d4ff',
    description: 'Build cross-platform iOS and Android apps using React Native and Expo framework.',
    tags: ['React Native', 'Expo', 'iOS', 'Android'],
    featured: false,
    bestseller: true,
    curriculum: [
      { section: 'React Native Basics', lessons: ['Components', 'Navigation', 'Styling'] },
      { section: 'Advanced Features', lessons: ['Native APIs', 'Push Notifications', 'App Store Deployment'] },
    ]
  },
];

export const CATEGORIES = ['All', 'Web Development', 'Data Science', 'Design', 'Cloud Computing', 'Security', 'Mobile Development'];

export const INSTRUCTORS = [
  { id: 1, name: 'Dr. Sarah Mitchell', courses: 8, students: 45000, rating: 4.9, bio: 'Full-stack developer with 12+ years of experience.' },
  { id: 2, name: 'Prof. James Chen', courses: 6, students: 62000, rating: 4.8, bio: 'Data scientist at Google, PhD from MIT.' },
  { id: 3, name: 'Emma Rodriguez', courses: 5, students: 28000, rating: 4.7, bio: 'Senior UX Designer at Apple with a passion for teaching.' },
];

export const STATS = {
  totalStudents: '120,000+',
  totalCourses: '500+',
  totalInstructors: '200+',
  satisfaction: '98%',
};
